import type {
  Task,
  WorkflowRequest,
  ActivityItem,
  Department,
  TeamMember,
  WorkflowMetric,
} from "@/types/dashboard";

// ─── Mock Tasks ────────────────────────────────────────────────
export const MOCK_TASKS: Task[] = [
  {
    id: "TSK-1024",
    title: "Review purchase order #8821",
    description:
      "Verify the purchase order submitted by the procurement department for office supplies. Check budget allocation, vendor details, and compliance with procurement policy. Approve or send back with comments.",
    status: "pending",
    priority: "high",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_admin",
    assignedByName: "Sarah Chen",
    workflowId: "wf_procurement",
    workflowName: "Procurement Approval",
    departmentOrigin: "Procurement",
    createdAt: "2026-02-15T09:30:00Z",
    dueDate: "2026-02-17T17:00:00Z",
    tags: ["approval", "finance"],
    stepNumber: 3,
    totalSteps: 5,
  },
  {
    id: "TSK-1025",
    title: "Onboard new employee — Raj Patel",
    description:
      "Complete the IT onboarding checklist for Raj Patel joining the Engineering department. Set up workstation, create accounts, assign access badges, and schedule orientation sessions.",
    status: "in_progress",
    priority: "medium",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_hr",
    assignedByName: "Mike Torres",
    workflowId: "wf_onboarding",
    workflowName: "Employee Onboarding",
    departmentOrigin: "Human Resources",
    createdAt: "2026-02-14T11:00:00Z",
    dueDate: "2026-02-18T17:00:00Z",
    tags: ["onboarding", "IT"],
    stepNumber: 2,
    totalSteps: 6,
  },
  {
    id: "TSK-1026",
    title: "Approve leave request — Annual Leave",
    description:
      "Review and approve annual leave request from team member Lisa Wong for Feb 20-24. Check team capacity and workload coverage during absence period.",
    status: "pending",
    priority: "low",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_system",
    assignedByName: "System (Auto-Routed)",
    workflowId: "wf_leave",
    workflowName: "Leave Management",
    departmentOrigin: "Engineering",
    createdAt: "2026-02-16T08:15:00Z",
    dueDate: "2026-02-19T12:00:00Z",
    tags: ["approval", "HR"],
    stepNumber: 2,
    totalSteps: 3,
  },
  {
    id: "TSK-1020",
    title: "Submit Q4 expense report",
    description:
      "Compile and submit all Q4 expenses including travel, client entertainment, and software subscriptions. Attach receipts and categorize line items.",
    status: "completed",
    priority: "medium",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_finance",
    assignedByName: "Amy Liu",
    workflowId: "wf_expense",
    workflowName: "Expense Reporting",
    departmentOrigin: "Finance",
    createdAt: "2026-02-10T14:00:00Z",
    dueDate: "2026-02-14T17:00:00Z",
    completedAt: "2026-02-13T16:30:00Z",
    tags: ["finance", "report"],
    stepNumber: 4,
    totalSteps: 4,
  },
  {
    id: "TSK-1018",
    title: "Escalated: Server migration sign-off",
    description:
      "This task was escalated due to SLA breach. The server migration plan requires CTO sign-off before weekend maintenance window. Original deadline was Feb 12.",
    status: "escalated",
    priority: "critical",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_devops",
    assignedByName: "Jake Morrison",
    workflowId: "wf_infra",
    workflowName: "Infrastructure Change",
    departmentOrigin: "DevOps",
    createdAt: "2026-02-08T10:00:00Z",
    dueDate: "2026-02-12T17:00:00Z",
    escalatedAt: "2026-02-13T09:00:00Z",
    tags: ["infrastructure", "critical"],
    stepNumber: 4,
    totalSteps: 7,
  },
  {
    id: "TSK-1027",
    title: "Review marketing campaign brief",
    description:
      "Review the Q1 campaign brief submitted by the marketing team. Verify budget allocation, target audience segments, and messaging alignment with brand guidelines.",
    status: "overdue",
    priority: "high",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_marketing",
    assignedByName: "Nina Kapoor",
    workflowId: "wf_campaign",
    workflowName: "Campaign Approval",
    departmentOrigin: "Marketing",
    createdAt: "2026-02-11T09:00:00Z",
    dueDate: "2026-02-15T17:00:00Z",
    tags: ["marketing", "approval"],
    stepNumber: 2,
    totalSteps: 4,
  },
  {
    id: "TSK-1019",
    title: "Vendor contract renewal — CloudServe",
    description:
      "Sent back for revision: pricing terms need renegotiation. Original approval was rejected due to 15% price increase exceeding budget threshold.",
    status: "sent_back",
    priority: "medium",
    assignedTo: "user_1",
    assignedToName: "You",
    assignedBy: "user_legal",
    assignedByName: "David Kim",
    workflowId: "wf_vendor",
    workflowName: "Vendor Management",
    departmentOrigin: "Legal",
    createdAt: "2026-02-09T13:00:00Z",
    dueDate: "2026-02-20T17:00:00Z",
    sentBackAt: "2026-02-14T11:00:00Z",
    sentBackReason: "Pricing terms exceed approved budget threshold by 15%. Renegotiate or provide justification.",
    tags: ["vendor", "contract"],
    stepNumber: 3,
    totalSteps: 5,
  },
];

// ─── Mock Requests ─────────────────────────────────────────────
export const MOCK_REQUESTS: WorkflowRequest[] = [
  {
    id: "REQ-501",
    title: "New laptop request",
    workflowName: "IT Asset Request",
    status: "in_progress",
    submittedBy: "user_1",
    submittedByName: "You",
    submittedAt: "2026-02-14T10:00:00Z",
    currentStep: "Manager Approval",
    totalSteps: 4,
    completedSteps: 1,
    lastUpdated: "2026-02-15T14:20:00Z",
  },
  {
    id: "REQ-502",
    title: "Travel reimbursement — NYC conference",
    workflowName: "Expense Reporting",
    status: "approved",
    submittedBy: "user_1",
    submittedByName: "You",
    submittedAt: "2026-02-10T08:30:00Z",
    currentStep: "Finance Processing",
    totalSteps: 3,
    completedSteps: 3,
    lastUpdated: "2026-02-13T16:45:00Z",
    approver: "Amy Liu",
  },
  {
    id: "REQ-503",
    title: "Office space relocation",
    workflowName: "Facilities Management",
    status: "submitted",
    submittedBy: "user_1",
    submittedByName: "You",
    submittedAt: "2026-02-16T07:00:00Z",
    currentStep: "Awaiting Review",
    totalSteps: 5,
    completedSteps: 0,
    lastUpdated: "2026-02-16T07:00:00Z",
  },
  {
    id: "REQ-490",
    title: "Software license — Figma Enterprise",
    workflowName: "IT Asset Request",
    status: "rejected",
    submittedBy: "user_1",
    submittedByName: "You",
    submittedAt: "2026-02-05T09:00:00Z",
    currentStep: "Closed",
    totalSteps: 4,
    completedSteps: 2,
    lastUpdated: "2026-02-07T11:00:00Z",
  },
  {
    id: "REQ-505",
    title: "Annual performance review submission",
    workflowName: "Performance Review",
    status: "completed",
    submittedBy: "user_1",
    submittedByName: "You",
    submittedAt: "2026-02-01T10:00:00Z",
    currentStep: "Completed",
    totalSteps: 3,
    completedSteps: 3,
    lastUpdated: "2026-02-08T14:00:00Z",
  },
];

// ─── Mock Activity Feed ────────────────────────────────────────
export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    type: "task_assigned",
    message: 'New task assigned: "Review purchase order #8821"',
    actor: "Sarah Chen",
    timestamp: "2026-02-16T09:30:00Z",
    relatedId: "TSK-1024",
  },
  {
    id: "act-2",
    type: "request_approved",
    message: 'Your request "Travel reimbursement" was approved',
    actor: "Amy Liu",
    timestamp: "2026-02-15T16:45:00Z",
    relatedId: "REQ-502",
  },
  {
    id: "act-3",
    type: "task_escalated",
    message: 'Task "Server migration sign-off" escalated — SLA breach',
    actor: "System",
    timestamp: "2026-02-15T09:00:00Z",
    relatedId: "TSK-1018",
  },
  {
    id: "act-4",
    type: "task_completed",
    message: 'You completed "Submit Q4 expense report"',
    actor: "You",
    timestamp: "2026-02-13T16:30:00Z",
    relatedId: "TSK-1020",
  },
  {
    id: "act-5",
    type: "member_joined",
    message: "Raj Patel joined the Engineering department",
    actor: "System",
    timestamp: "2026-02-14T08:00:00Z",
  },
  {
    id: "act-6",
    type: "workflow_published",
    message: 'Workflow "Vendor Management v2" published by admin',
    actor: "David Kim",
    timestamp: "2026-02-12T15:00:00Z",
  },
  {
    id: "act-7",
    type: "request_submitted",
    message: 'New request submitted: "Office space relocation"',
    actor: "You",
    timestamp: "2026-02-16T07:00:00Z",
    relatedId: "REQ-503",
  },
];

// ─── Mock Departments ──────────────────────────────────────────
export const MOCK_DEPARTMENTS: Department[] = [
  { id: "dept-1", name: "Engineering", head: "Sarah Chen", memberCount: 24, activeWorkflows: 8 },
  { id: "dept-2", name: "Human Resources", head: "Mike Torres", memberCount: 8, activeWorkflows: 5 },
  { id: "dept-3", name: "Finance", head: "Amy Liu", memberCount: 12, activeWorkflows: 6 },
  { id: "dept-4", name: "Marketing", head: "Nina Kapoor", memberCount: 15, activeWorkflows: 4 },
  { id: "dept-5", name: "DevOps", head: "Jake Morrison", memberCount: 10, activeWorkflows: 7 },
  { id: "dept-6", name: "Legal", head: "David Kim", memberCount: 6, activeWorkflows: 3 },
];

// ─── Mock Team Members ─────────────────────────────────────────
export const MOCK_TEAM: TeamMember[] = [
  { id: "tm-1", name: "Sarah Chen", email: "sarah@flowengine.io", role: "admin", department: "Engineering", isActive: true, tasksCompleted: 47, tasksPending: 3, lastActive: "2026-02-16T10:00:00Z" },
  { id: "tm-2", name: "Mike Torres", email: "mike@flowengine.io", role: "admin", department: "Human Resources", isActive: true, tasksCompleted: 32, tasksPending: 5, lastActive: "2026-02-16T09:45:00Z" },
  { id: "tm-3", name: "Amy Liu", email: "amy@flowengine.io", role: "employee", department: "Finance", isActive: true, tasksCompleted: 58, tasksPending: 2, lastActive: "2026-02-16T08:30:00Z" },
  { id: "tm-4", name: "Nina Kapoor", email: "nina@flowengine.io", role: "employee", department: "Marketing", isActive: true, tasksCompleted: 29, tasksPending: 7, lastActive: "2026-02-15T17:00:00Z" },
  { id: "tm-5", name: "Jake Morrison", email: "jake@flowengine.io", role: "employee", department: "DevOps", isActive: false, tasksCompleted: 41, tasksPending: 1, lastActive: "2026-02-14T12:00:00Z" },
  { id: "tm-6", name: "David Kim", email: "david@flowengine.io", role: "analyst", department: "Legal", isActive: true, tasksCompleted: 23, tasksPending: 4, lastActive: "2026-02-16T10:15:00Z" },
  { id: "tm-7", name: "Lisa Wong", email: "lisa@flowengine.io", role: "employee", department: "Engineering", isActive: true, tasksCompleted: 36, tasksPending: 6, lastActive: "2026-02-16T09:00:00Z" },
  { id: "tm-8", name: "Raj Patel", email: "raj@flowengine.io", role: "employee", department: "Engineering", isActive: true, tasksCompleted: 0, tasksPending: 1, lastActive: "2026-02-16T07:30:00Z" },
];

// ─── Mock Workflow Metrics ─────────────────────────────────────
export const MOCK_METRICS: WorkflowMetric[] = [
  { workflowName: "Procurement Approval", totalRuns: 142, avgCompletionTime: "2.3 days", successRate: 94, bottleneckStep: "Finance Review" },
  { workflowName: "Employee Onboarding", totalRuns: 38, avgCompletionTime: "4.1 days", successRate: 100 },
  { workflowName: "Leave Management", totalRuns: 215, avgCompletionTime: "0.8 days", successRate: 97 },
  { workflowName: "Expense Reporting", totalRuns: 189, avgCompletionTime: "1.5 days", successRate: 91, bottleneckStep: "Manager Approval" },
  { workflowName: "IT Asset Request", totalRuns: 76, avgCompletionTime: "3.2 days", successRate: 85, bottleneckStep: "Budget Approval" },
  { workflowName: "Infrastructure Change", totalRuns: 22, avgCompletionTime: "5.7 days", successRate: 78, bottleneckStep: "CTO Sign-off" },
];
